### ISSUE TITLE
404 not found loading dist files

### ISSUE THREAD

**Issue by evansendra** [mikemcgowan/django-react#1]
After running through the installation commands, I can't get any of the examples to run.  I see the following in my JS console:

    localhost/:6 GET http://localhost:8000/static/js/components/bootstrap/dist/css/bootstrap.min.css 
    localhost/:27 GET http://localhost:8000/static/js/components/bootstrap/dist/js/bootstrap.min.js 
    localhost/:26 GET http://localhost:8000/static/js/components/jquery/dist/jquery.min.js 
    localhost/:31 GET http://localhost:8000/static/js/build/app/vendor/vendor.js 
    localhost/:32 GET http://localhost:8000/static/js/build/app/router/router.js 404 (NOT FOUND)

**Comment by mikemcgowan** [comment]
Hi there!

It looks like `JS_DEBUG = True` in your `settings.py`, so it's trying to load the non-minified builds (which haven't been built yet, hence the 404s).

You could either set `JS_DEBUG = False` so it tries to load the minified builds, or build the non-minified files with:

```
gulp watch --nowatch --app vendor
gulp watch --nowatch --app comments
gulp watch --nowatch --app router
gulp watch --nowatch --app thinking_in_react
```

The `README.md` could probably be clearer here.

**Comment by mikemcgowan** [comment]
I've updated `README.md`.
